Maharaja_Hotel/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project-design/', include('ProjectDesign.urls', namespace='ProjectDesign')),
    path('project-model/', include('ProjectModel.urls', namespace='ProjectModel')),
    path('', include('ProjectReal.urls', namespace='ProjectReal')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ProjectDesign/urls.py
from django.urls import path
from .views import (
    entry_view,

    # Home Model
    home_list_view,
    home_create_view,
    home_retrieve_view,
    home_update_view,
    home_delete_view,

    # Category Model
    category_list_view,
    category_create_view,
    category_retrieve_view,
    category_update_view,
    category_delete_view,

    # Product Model
    product_list_view,
    product_create_view,
    product_retrieve_view,
    product_update_view,
    product_delete_view,

    # About Model
    about_list_view,
    about_create_view,
    about_retrieve_view,
    about_update_view,
    about_delete_view,

)


app_name = 'ProjectDesign'

urlpatterns = [
    # Entry
    path('', entry_view, name='entry-page'),

    # Home Model
    path('home-list-page/', home_list_view, name='home-list-page'),
    path('home-create-page/', home_create_view, name='home-create-page'),
    path('home-retrieve-page/<slug>/', home_retrieve_view, name='home-retrieve-page'),
    path('home-update-page/<slug>/', home_update_view, name='home-update-page'),
    path('home-delete-page/<slug>/', home_delete_view, name='home-delete-page'),

    # Category Model
    path('category-list-page/', category_list_view, name='category-list-page'),
    path('category-create-page/', category_create_view, name='category-create-page'),
    path('category-retrieve-page/<slug>/', category_retrieve_view, name='category-retrieve-page'),
    path('category-update-page/<slug>/', category_update_view, name='category-update-page'),
    path('category-delete-page/<slug>/', category_delete_view, name='category-delete-page'),

    # Product Model
    path('product-list-page/', product_list_view, name='product-list-page'),
    path('product-create-page/', product_create_view, name='product-create-page'),
    path('product-retrieve-page/<slug>/', product_retrieve_view, name='product-retrieve-page'),
    path('product-update-page/<slug>/', product_update_view, name='product-update-page'),
    path('product-delete-page/<slug>/', product_delete_view, name='product-delete-page'),

    # About Model
    path('about-list-page/', about_list_view, name='about-list-page'),
    path('about-create-page/', about_create_view, name='about-create-page'),
    path('about-retrieve-page/<slug>/', about_retrieve_view, name='about-retrieve-page'),
    path('about-update-page/<slug>/', about_update_view, name='about-update-page'),
    path('about-delete-page/<slug>/', about_delete_view, name='about-delete-page'),

]

ProjectReal/urls.py
from django.urls import path
from .views import (
    home_view,
)

app_name = 'ProjectReal'

urlpatterns = [
    path('', home_view, name='home-page'),
]

ProjectDesign/forms.py
from django import forms
from .models import (
    Home,
    Category,
    Product,
    About,
)

# Home Model
class HomeForm(forms.ModelForm):
    class Meta:
        model = Home
        fields = '__all__'

    def get_class_name(self):
        return self.__class__.__name__


# Category Model
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def get_class_name(self):
        return self.__class__.__name__


# Product Model
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def get_class_name(self):
        return self.__class__.__name__


# About Model
class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = '__all__'

    def get_class_name(self):
        return self.__class__.__name__

ProjectDesign/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from .models import (
    Home,
    Category,
    Product,
    About,
)
from .forms import (
    HomeForm,
    CategoryForm,
    ProductForm,
    AboutForm,
)


# Entry
def entry_view(request):
    template_name = 'ProjectDesign/entry-page.html'
    context = {
        'title': 'Entry Page'
    }
    return render(request, template_name, context)


# Home Model (LCRUD)
# Home List
@staff_member_required()
def home_list_view(request):
    objects_list = Home.objects.all()

    template_name = 'ProjectDesign/Home/a-home-list-page.html'
    context = {
        'title': 'Home List',
        'objects_list': objects_list
    }
    return render(request, template_name, context)

# Home Create
@staff_member_required()
def home_create_view(request):
    if request.method == 'POST':
        form = HomeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:home-list-page')
    else:
        form = HomeForm()

    template_name = 'ProjectDesign/Home/b-home-create-page.html'
    context = {
        'title': 'Home Create',
        'object_form': form,
    }
    return render(request, template_name, context)

# Home Retrieve
@staff_member_required()
def home_retrieve_view(request, slug):
    object = get_object_or_404(Home, slug=slug)

    template_name = 'ProjectDesign/Home/c-home-retrieve-page.html'
    context = {
        'title': 'Home Retrieve',
        'object': object,
    }
    return render(request, template_name, context)

# Home Update
@staff_member_required()
def home_update_view(request, slug):
    object = get_object_or_404(Home, slug=slug)

    if request.method == 'POST':
        form = HomeForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:home-list-page')
    else:
        form = HomeForm(instance=object)

    template_name = 'ProjectDesign/Home/d-home-update-page.html'
    context = {
        'title': 'Home Update',
        'object_form': form,
    }
    return render(request, template_name, context)

# Home Delete
@staff_member_required()
def home_delete_view(request, slug):
    if request.method == 'POST':
        object = get_object_or_404(Home, slug=slug)
        object.delete()
        return redirect('ProjectDesign:home-list-page')
    else:
        object = get_object_or_404(Home, slug=slug)

    template_name = 'ProjectDesign/Home/e-home-delete-page.html'
    context = {
        'title': 'Home Delete',
        'object': object,
    }
    return render(request, template_name, context)


# Category Model (LCRUD)
# Category List
@staff_member_required()
def category_list_view(request):
    objects_list = Category.objects.all()

    template_name = 'ProjectDesign/Category/a-category-list-page.html'
    context = {
        'title': 'Category List',
        'objects_list': objects_list
    }
    return render(request, template_name, context)

# Category Create
@staff_member_required()
def category_create_view(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:category-list-page')
    else:
        form = CategoryForm()

    template_name = 'ProjectDesign/Category/b-category-create-page.html'
    context = {
        'title': 'Category Create',
        'object_form': form,
    }
    return render(request, template_name, context)

# Category Retrieve
@staff_member_required()
def category_retrieve_view(request, slug):
    object = get_object_or_404(Category, slug=slug)

    template_name = 'ProjectDesign/Category/c-category-retrieve-page.html'
    context = {
        'title': 'Category Retrieve',
        'object': object,
    }
    return render(request, template_name, context)

# Category Update
@staff_member_required()
def category_update_view(request, slug):
    object = get_object_or_404(Category, slug=slug)

    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:category-list-page')
    else:
        form = CategoryForm(instance=object)

    template_name = 'ProjectDesign/Category/d-category-update-page.html'
    context = {
        'title': 'Category Update',
        'object_form': form,
    }
    return render(request, template_name, context)

# Category Delete
@staff_member_required()
def category_delete_view(request, slug):
    if request.method == 'POST':
        object = get_object_or_404(Category, slug=slug)
        object.delete()
        return redirect('ProjectDesign:category-list-page')
    else:
        object = get_object_or_404(Category, slug=slug)

    template_name = 'ProjectDesign/Category/e-category-delete-page.html'
    context = {
        'title': 'Category Delete',
        'object': object,
    }
    return render(request, template_name, context)


# Product Model (LCRUD)
# Product List
@staff_member_required()
def product_list_view(request):
    objects_list = Product.objects.all()

    template_name = 'ProjectDesign/Product/a-product-list-page.html'
    context = {
        'title': 'Product List',
        'objects_list': objects_list
    }
    return render(request, template_name, context)

# Product Create
@staff_member_required()
def product_create_view(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:product-list-page')
    else:
        form = ProductForm()

    template_name = 'ProjectDesign/Product/b-product-create-page.html'
    context = {
        'title': 'Product Create',
        'object_form': form,
    }
    return render(request, template_name, context)

# Product Retrieve
@staff_member_required()
def product_retrieve_view(request, slug):
    object = get_object_or_404(Product, slug=slug)

    template_name = 'ProjectDesign/Product/c-product-retrieve-page.html'
    context = {
        'title': 'Product Retrieve',
        'object': object,
    }
    return render(request, template_name, context)

# Product Update
@staff_member_required()
def product_update_view(request, slug):
    object = get_object_or_404(Product, slug=slug)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:product-list-page')
    else:
        form = ProductForm(instance=object)

    template_name = 'ProjectDesign/Product/d-product-update-page.html'
    context = {
        'title': 'Product Update',
        'object_form': form,
    }
    return render(request, template_name, context)

# Product Delete
@staff_member_required()
def product_delete_view(request, slug):
    if request.method == 'POST':
        object = get_object_or_404(Product, slug=slug)
        object.delete()
        return redirect('ProjectDesign:product-list-page')
    else:
        object = get_object_or_404(Product, slug=slug)

    template_name = 'ProjectDesign/Product/e-product-delete-page.html'
    context = {
        'title': 'Product Delete',
        'object': object,
    }
    return render(request, template_name, context)


# About Model (LCRUD)
# About List
@staff_member_required()
def about_list_view(request):
    objects_list = About.objects.all()

    template_name = 'ProjectDesign/About/a-about-list-page.html'
    context = {
        'title': 'About List',
        'objects_list': objects_list
    }
    return render(request, template_name, context)

# About Create
@staff_member_required()
def about_create_view(request):
    if request.method == 'POST':
        form = AboutForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:about-list-page')
    else:
        form = AboutForm()

    template_name = 'ProjectDesign/About/b-about-create-page.html'
    context = {
        'title': 'About Create',
        'object_form': form,
    }
    return render(request, template_name, context)

# About Retrieve
@staff_member_required()
def about_retrieve_view(request, slug):
    object = get_object_or_404(About, slug=slug)

    template_name = 'ProjectDesign/About/c-about-retrieve-page.html'
    context = {
        'title': 'About Retrieve',
        'object': object,
    }
    return render(request, template_name, context)

# About Update
@staff_member_required()
def about_update_view(request, slug):
    object = get_object_or_404(About, slug=slug)

    if request.method == 'POST':
        form = AboutForm(request.POST, request.FILES, instance=object)
        if form.is_valid():
            form.save()
            return redirect('ProjectDesign:about-list-page')
    else:
        form = AboutForm(instance=object)

    template_name = 'ProjectDesign/About/d-about-update-page.html'
    context = {
        'title': 'About Update',
        'object_form': form,
    }
    return render(request, template_name, context)

# About Delete
@staff_member_required()
def about_delete_view(request, slug):
    if request.method == 'POST':
        object = get_object_or_404(About, slug=slug)
        object.delete()
        return redirect('ProjectDesign:about-list-page')
    else:
        object = get_object_or_404(About, slug=slug)

    template_name = 'ProjectDesign/About/e-about-delete-page.html'
    context = {
        'title': 'About Delete',
        'object': object,
    }
    return render(request, template_name, context)

ProjectDesign/templates/ProjectDesign/About/a-about-list-page.html
{% extends 'ProjectDesign/extras/base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-10 mx-auto">

        <!-- Heading -->
        <div class="flex flex-col text-center w-full mb-10">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                {{ objects_list.first.get_class_name }} List Page
            </h1>
            <div class="flex pt-5 justify-center">
                <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
        </div>

        <!-- List Items -->
        <div class="flex flex-col justify-center mb-10 w-full">
            <a href="{% url 'ProjectDesign:entry-page' %}" class="mx-auto text-white bg-indigo-500 border-0 py-2 px-5 mb-2 focus:outline-none hover:bg-indigo-600 rounded text-lg">Go Back</a>
            <a href="{% url 'ProjectDesign:about-create-page' %}" class="mx-auto text-white bg-indigo-500 border-0 py-2 px-5 focus:outline-none hover:bg-indigo-600 rounded text-lg">Create</a>
        </div>

        <div class="flex flex-wrap -m-4 justify-center">
            {% for object in objects_list %}
            <div class="p-4 md:w-1/3 text-center items-center">
                <div class="h-full border-2 border-indigo-500 border-opacity-60 rounded-lg overflow-hidden">
                    <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{ object.image.url }}" alt="blog">
                    <div class="p-6">
                        <h1 class="title-font text-lg font-medium text-gray-900 mb-1">{{ object.title }}</h1>
                        <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 uppercase mb-3">{{ object.subtitle }}</h2>
                        <div class="flex p-2 mt-2 w-full">
                            <a href="{{ object.get_object_retrieve_url }}" class="mx-auto text-white bg-indigo-500 border-0 py-2 px-5 mx-2 focus:outline-none hover:bg-indigo-600 rounded text-lg">Retrieve</a>
                            <a href="{{ object.get_object_update_url }}" class="mx-auto text-white bg-indigo-500 border-0 py-2 px-5 mx-2 focus:outline-none hover:bg-indigo-600 rounded text-lg">Update</a>
                            <a href="{{ object.get_object_delete_url }}" class="mx-auto text-white bg-indigo-500 border-0 py-2 px-5 mx-2 focus:outline-none hover:bg-indigo-600 rounded text-lg">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</section>
{% endblock content %}

ProjectDesign/templates/ProjectDesign/About/b-about-create-page.html
{% extends 'ProjectDesign/extras/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="text-gray-600 body-font relative">
    <div class="container px-5 py-10 mx-auto">

        <!-- Heading -->
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                {{ object_form.get_class_name | slice:":-4" }} Create Page
            </h1>
            <div class="flex pt-5 justify-center">
                <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
        </div>

        <!-- Create Form -->
        <div class="lg:w-1/2 md:w-2/3 mx-auto">
            <div class="flex flex-wrap -m-2 justify-center text-center">
                <form class="flex flex-col items-center p-2 w-1/2" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ object_form.media }}
                    {{ object_form | crispy }}
                    <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 mt-5 focus:outline-none hover:bg-indigo-600 rounded text-lg"
                        type="submit">Create</button>
                </form>
            </div>
        </div>

    </div>
</section>
{% endblock content %}

ProjectDesign/templates/ProjectDesign/About/c-about-retrieve-page.html
{% extends 'ProjectDesign/extras/base.html' %}

{% block content %}
<section class="text-gray-600 body-font relative">
    <div class="container px-5 py-10 mx-auto">

        <!-- Heading -->
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                {{ object.get_class_name }} Retrieve Page
            </h1>
            <div class="flex pt-5 justify-center">
                <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
        </div>

        <!-- Retrieve -->
        <div class="flex flex-col items-center justify-center px-5">
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{{ object.image.url }}">
            <div class="text-center lg:w-2/3 w-full">
                <h1 class="title-font sm:text-4xl text-3xl mb-2 font-medium text-gray-900">{{ object.title }}</h1>
                <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 uppercase mb-4">{{ object.subtitle }}</h2>
                <div class="mb-8 leading-relaxed">{{ object.description | safe }}</div>
                <div class="flex justify-center">
                    <a href="{{ object.get_object_update_url }}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Update</a>
                    <a href="{{ object.get_object_delete_url }}" class="ml-4 inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Delete</a>
                </div>
            </div>
        </div>

    </div>
</section>
{% endblock content %}

ProjectDesign/templates/ProjectDesign/About/d-about-update-page.html
{% extends 'ProjectDesign/extras/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="text-gray-600 body-font relative">
    <div class="container px-5 py-10 mx-auto">

        <!-- Heading -->
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                {{ object_form.get_class_name | slice:":-4" }} Update Page
            </h1>
            <div class="flex pt-5 justify-center">
                <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
        </div>

        <!-- Update Form -->
        <div class="lg:w-1/2 md:w-2/3 mx-auto">
            <div class="flex flex-wrap -m-2 justify-center text-center">
                <form class="flex flex-col items-center p-2 w-1/2" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ object_form.media }}
                    {{ object_form | crispy }}
                    <button class="flex mx-auto text-white bg-indigo-500 border-0 py-2 px-8 mt-5 focus:outline-none hover:bg-indigo-600 rounded text-lg"
                        type="submit">Update</button>
                </form>
            </div>
        </div>

    </div>
</section>
{% endblock content %}

ProjectDesign/templates/ProjectDesign/About/e-about-delete-page.html
{% extends 'ProjectDesign/extras/base.html' %}

{% block content %}
<section class="text-gray-600 body-font relative">
    <div class="container px-5 py-10 mx-auto">

        <!-- Heading -->
        <div class="flex flex-col text-center w-full mb-12">
            <h1 class="sm:text-3xl text-2xl font-medium title-font text-gray-900">
                {{ object.get_class_name }} Delete Page
            </h1>
            <div class="flex pt-5 justify-center">
                <div class="w-16 h-1 rounded-full bg-indigo-500 inline-flex"></div>
            </div>
        </div>

        <!-- Delete -->
        <div class="flex flex-col text-center w-full mb-12">
            <form method="POST">
                {% csrf_token %}
                <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Do you really want to delete "{{ object }}"?</p>

                <div class="flex justify-center mt-5">
                    <a href="{{ object.get_object_list_url }}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Cancel</a>
                    <button type="submit" class="ml-4 inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Yes, Sure</button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}